## 📙 정리하기

### 에러 처리의 필요성
try...catch문을 이용해 오류가 발생해도 프로그램을 종료시키지 않고 코드를 실행시킬 수 있다.

```javascript
console.log('[Start]');

foo(); // ReferenceError: foo is not defined
// 발생한 에러를 방치하면 프로그램은 강제 종료된다.

// 에러에 의해 프로그램이 강제 종료되어 아래 코드는 실행되지 않는다.
console.error('[에러 발생]', error); 
```

```javascript
console.log('[Start]');

try {
  foo(); 
} cahtch (error) {
  console.error('[에러 발생]', error);
  // [에러 발생] ReferenceError: foo is not defined
}
```

옵셔널 체이닝을 이용해서 아래 코드의 오류에 대응할 수 있지만 예외적인 상황이 너무나도 많기 때문에 모든 코드의 오류에 대응하기가 쉽지않다.
```javacsript
const $button = document.querySelector('button');

// TypeError: Cannot react property 'classList' of null
$button.classList.add('disabled');
```

### try...catch...finally문
try...catch...finally문을 이용하면 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 할 수 있다.
```javascript
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다. 
}
```

### Error 객체
Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다. message 프로퍼티의 값은 Error 생성자 함수에 인수로 전달한 에러 메세지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열이다.

| 생성자 함수 | 인스턴스 |
|:---:|:---:|
| Error | 일반적 에러 객체 |
| SyntaxError | 자바스크립트 문법에 맞지 않는 문을 해설할 때 발생하는 에러 객체 |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 |
| TypeError | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체 |
| RangeError | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체 |
| URIError | encodeURI 또는 decodeURI 함수에 부적적한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError | eval 함수에서 발생하는 에러 객체 |

### throw 문
에러 객체를 생성한다고 에러가 발생하진 않는다.
```javascript
try {
  new Error('something wrong'); 
} catch (error) {
  console.log(error)
}
```
에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객체를 던져야 한다.
```javascript
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error('something wrong');
} catch (error) {
  console.log(error); 
}
```

### 에러의 전파
에러는 **호출자 방향**으로 전파된다. 푸시되기 전 실행 컨텍스트 방향으로 전파된다.
```javascript
const foo = () => {
  throw Error('foo에서 발생한 에러'); 
};

const bar = () => {
  foo(); 
};

const baz = () => {
  bar(); 
};

try {
  baz(); 
} catch(error) {
  console.error(err 
}
```

> ### ✋ 주의할 점
비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없기 때문에 에러 전파할 수 없다.